# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='QuoteApp.User'),
            preserve_default=False,
        ),
    ]
